Exploratory analysis
b-cubed-eu/comp-unstructured-data pull request #2
Opened 2024-11-04 12:01 UTC by EmmaCartuyvels1

First exploratory analysis, start of comparing indicators

2025-01-22 14:43 UTC, wlangera reviewed
- Could you add in the beginning of each RMarkdown file a short introduction what the aim is of the analyses in that file? Or maybe can you number the RMarkdown file names so the order is clear?
- "dwca-rl-flanders-validated-checklist-v1.7" Can you put these files under version control? Or if they are to large, explain where and how people can download them?

2025-01-22 16:02 UTC, wlangera requested changes
Hi, some small things and general suggestions.

Less urgent coding style suggestions are done in PR #3

2025-01-27 10:02 UTC, wlangera commented
Comment from our meeting.
Maybe we should download the cube again using **rgbif** to make it more reproducible.

2025-03-03 12:38 UTC, EmmaCartuyvels1 commented on source/expl_analysis.Rmd
> +comp_range_data |>
Done

2025-03-03 12:39 UTC, EmmaCartuyvels1 commented on source/expl_analysis.Rmd
> +  perc_overlap_all <- (overlap_all_abv_cube / 936) * 100
Is no longer hard coded

2025-03-03 12:41 UTC, wlangera approved these changes

2025-03-03 12:42 UTC, merged